server.port=8087

spring.application.name=search-service

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# URLs des services
book-service.url=http://localhost:8082
inventory-service.url=http://localhost:8086
```

## 3.4 Structure des fichiers
```
search-service/
└── src/main/java/tn/tp/bibliotheque/search_service/
├── SearchServiceApplication.java
├── config/
│   └── WebClientConfig.java
├── controller/
│   └── SearchController.java
├── dto/
│   ├── BookDto.java
│   ├── InventoryDto.java
│   └── BookSearchResult.java
└── service/
└── SearchService.java